# basic
title: 1 Project Per Month
subtitle: plan, build, learn, repeat :)
favicon: favicon.ico

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
avatar: images/1PPM_Logo.png
banner_small: images/1ppm-banner-small.png
banner_large: images/1ppm-banner-large.png

# disqus
disqus_shortname: 1ppm

# social
social:
  github: https://github.com/1ppm
  twitter: https://github.com/1ppm/1ppmLog
  medium: http://medium.com/1ppm

# nav #
nav:
  home: .
  archive: archives
  # about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false


google_anlytics: UA-89690220-1
